<?php
/**
 * Base class of the API controllers.
 * An API controller exposes the operations of the component controller (list, view, add, edit, delete,
 * logical delete, undelete, trashed list) as JSON, with the same Model class and without any View.
 *
 * Called through api.php, see the documentation at the top of that file.
 */

declare(strict_types=1);
namespace Apgenic\Classes;

abstract class ControllerApi
{
    /** Model class of the component, ex: \Apgenic\Product\ModelProduct::class */
    const MODEL = '';
    /** Primary key field(s) */
    const PK = array();
    /** true if the primary key is generated by the database (AUTO_INCREMENT) */
    const PK_AUTO = true;
    /** true if the table has a deleted_at field (logical delete) */
    const SOFT_DELETE = false;
    /** Fields written by the model but filled by the API itself with the current date */
    const AUTO_DATES = array();
    /** Fields never sent in the answers */
    const HIDDEN = array();
    /**
     * Fields that can be written, the ones saved by add() and save() of the model.
     * name => array('type' => 'int'|'string', 'null' => bool, 'required' => bool, 'default' => mixed, 'max' => int, 'enum' => array)
     */
    const FIELDS = array();
    /** Tasks that can be called without being authenticated */
    const PUBLIC_TASKS = array();

    const DEFAULT_LIMIT = 10;
    const MAX_LIMIT = 200;

    /** All the fields of the table: returned in the answers, accepted as filter and as sort field */
    public static array $fieldsNames = array();

    /** Body of the request (JSON or form) */
    protected array $input = array();
    protected $data;


    /**
     * Read the request, check the access, execute the task and send the JSON answer
     * @return void
     */
    public function render():void{
        try{
            $this->input = $this->readInput();
            $method = $_SERVER['REQUEST_METHOD'];
            $task = $this->task($method);

            if(!in_array($task, static::PUBLIC_TASKS, true)){
                $this->authenticate($method, $task);
            }

            $modelClass = static::MODEL;
            $this->data = new $modelClass();
            if(!isset(Model::$db)){
                throw new ApiException(503, 'Database not available');
            }

            $this->dispatch($task, $method);
        }
        catch(ApiException $e){
            self::send($e->getCode(), array('success' => false, 'error' => array('code' => $e->getCode(), 'message' => $e->getMessage()) + $e->details));
        }
        catch(\PDOException $e){
            error_log('API '.static::class.': '.$e->getMessage());
            // 23000 = integrity constraint: duplicate key, unknown foreign key, row still referenced
            if(substr((string)$e->getCode(), 0, 2) == '23'){
                self::send(409, array('success' => false, 'error' => array('code' => 409, 'message' => 'The database refused the operation: duplicate value, unknown reference or row still used')));
            }
            else{
                self::send(500, array('success' => false, 'error' => array('code' => 500, 'message' => 'Database error')));
            }
        }
        catch(\Throwable $e){
            error_log('API '.static::class.': '.$e->getMessage());
            self::send(500, array('success' => false, 'error' => array('code' => 500, 'message' => 'Internal error')));
        }
    }


    /**
     * Task asked in the url, or deduced from the HTTP method
     * @return string
     */
    protected function task(string $method):string{
        $task = strtolower((string)($_GET['task'] ?? ''));

        if($task == ''){
            switch($method){
                case 'GET':    $task = $this->hasPk() ? 'view' : 'list'; break;
                case 'POST':   $task = $this->hasPk() && static::PK_AUTO ? 'edit' : 'add'; break;
                case 'PUT':
                case 'PATCH':  $task = 'edit'; break;
                case 'DELETE': $task = 'del'; break;
            }
        }

        // Names used by the controller of the web interface
        $aliases = array('editlist' => 'list', 'viewlist' => 'list', 'childlist' => 'list', 'delhtmx' => 'del',
                         'logicaldeletehtmx' => 'logicaldel', 'undelhtmx' => 'undel');
        return $aliases[$task] ?? $task;
    }


    /**
     * Execute the task
     * @return void
     */
    protected function dispatch(string $task, string $method):void{
        $softDelete = array('trashedlist', 'logicaldel', 'undel');
        if(in_array($task, $softDelete, true) && !static::SOFT_DELETE){
            throw new ApiException(404, 'Unknown task');
        }

        switch($task){
            case 'list':        self::allow($method, array('GET')); $this->getList(0); break;
            case 'trashedlist': self::allow($method, array('GET')); $this->getList(1); break;
            case 'view':        self::allow($method, array('GET')); $this->view(); break;
            case 'add':         self::allow($method, array('POST')); $this->add(); break;
            case 'edit':        self::allow($method, array('POST', 'PUT', 'PATCH')); $this->edit(); break;
            case 'del':         self::allow($method, array('POST', 'DELETE')); $this->del(); break;
            case 'logicaldel':  self::allow($method, array('POST', 'DELETE')); $this->logicalDel(); break;
            case 'undel':       self::allow($method, array('POST', 'PUT', 'PATCH')); $this->unDel(); break;
            default: throw new ApiException(404, 'Unknown task');
        }
    }


    // Tasks
    // ------------------------------------------------------------------------------------------------

    /**
     * List of rows, with filters, text search, sort and pagination
     * @param int $trashed 0 = rows not logically deleted, 1 = logically deleted rows
     * @return void
     */
    protected function getList(int $trashed):void{
        $filters = array();
        if(isset($_GET['filters']) && is_array($_GET['filters'])){
            foreach($_GET['filters'] as $field => $value){
                // Only known fields are accepted (the model checks the names again before writing them in the query)
                if(in_array($field, static::$fieldsNames, true) && !in_array($field, static::HIDDEN, true) && $field != 'deleted_at' && is_scalar($value)){
                    $filters[$field] = (string)$value;
                }
            }
        }
        if(static::SOFT_DELETE){
            $filters['deleted_at'] = $trashed;
        }

        $orderBy = (string)($_GET['orderBy'] ?? '');
        if(!in_array($orderBy, static::$fieldsNames, true) || in_array($orderBy, static::HIDDEN, true)){
            $orderBy = static::PK[0];
        }
        $order = strtolower((string)($_GET['order'] ?? 'desc')) == 'asc' ? 'ASC' : 'DESC';

        $limit = filter_var($_GET['limit'] ?? static::DEFAULT_LIMIT, FILTER_VALIDATE_INT);
        if($limit === false || $limit < 1){ $limit = static::DEFAULT_LIMIT; }
        $limit = min($limit, static::MAX_LIMIT);
        $page = max(1, (int)filter_var($_GET['page'] ?? 1, FILTER_VALIDATE_INT));

        $textSearch = (string)filter_var((string)($_GET['text_search'] ?? ''), FILTER_SANITIZE_SPECIAL_CHARS);

        $this->data->list = array();
        $total = $this->data->getList(($page - 1) * $limit, $limit, $filters, $orderBy, $order, $textSearch);

        $rows = array();
        foreach($this->data->list as $row){
            $rows[] = $this->export($row);
        }

        self::send(200, array(
            'success' => true,
            'data' => $rows,
            'meta' => array('total' => $total, 'page' => $page, 'limit' => $limit, 'pages' => (int)ceil($total / $limit)),
        ));
    }


    /**
     * One row
     * @return void
     */
    protected function view():void{
        $this->load();
        self::send(200, array('success' => true, 'data' => $this->record()));
    }


    /**
     * Create a row
     * @return void
     */
    protected function add():void{
        $errors = array();
        $pk = array();

        // A key that is not generated by the database is given by the caller
        if(!static::PK_AUTO){
            foreach(static::PK as $field){
                $value = filter_var($this->input[$field] ?? $_GET[$field] ?? null, FILTER_VALIDATE_INT);
                if($value === false || $value === null || $value < 1){
                    $errors[$field] = 'Required, positive integer';
                }
                else{
                    $pk[$field] = $value;
                    $this->data->$field = $value;
                }
            }
        }

        foreach(static::FIELDS as $field => $spec){
            if(isset($pk[$field])) continue;

            if(array_key_exists($field, $this->input)){
                $this->data->$field = $this->value($field, $spec, $this->input[$field], $errors);
            }
            elseif($spec['required']){
                $errors[$field] = 'Required';
            }
            else{
                $this->data->$field = $spec['default'] ?? ($spec['null'] ? null : ($spec['type'] == 'int' ? 0 : ''));
            }
        }
        foreach(static::AUTO_DATES as $field){
            $this->data->$field = date('Y-m-d H:i:s');
        }

        $this->validate($errors, true);
        if(count($errors)){
            throw new ApiException(422, 'Validation failed', array('fields' => $errors));
        }

        if(!$this->data->add()){
            throw new ApiException(500, 'The row could not be created');
        }

        // add() replaces the key by the last insert id, wrong when the key is not generated
        foreach($pk as $field => $value){
            $this->data->$field = $value;
        }
        $this->data->get();
        self::send(201, array('success' => true, 'data' => $this->record()));
    }


    /**
     * Update a row: only the fields sent are changed
     * @return void
     */
    protected function edit():void{
        $this->load();

        $errors = array();
        foreach(static::FIELDS as $field => $spec){
            if(in_array($field, static::PK, true)) continue;

            if(array_key_exists($field, $this->input)){
                $this->data->$field = $this->value($field, $spec, $this->input[$field], $errors);
            }
        }
        foreach(static::AUTO_DATES as $field){
            if($field != 'created_at'){
                $this->data->$field = date('Y-m-d H:i:s');
            }
        }

        $this->validate($errors, false);
        if(count($errors)){
            throw new ApiException(422, 'Validation failed', array('fields' => $errors));
        }

        if(!$this->data->save()){
            throw new ApiException(500, 'The row could not be saved');
        }

        $this->data->get();
        self::send(200, array('success' => true, 'data' => $this->record()));
    }


    /**
     * Delete a row for good
     * @return void
     */
    protected function del():void{
        $this->load();
        if(!$this->data->del()){
            throw new ApiException(500, 'The row could not be deleted');
        }
        self::send(200, array('success' => true, 'data' => $this->pkValues()));
    }


    /**
     * Logical delete: the row goes to the trashed list
     * @return void
     */
    protected function logicalDel():void{
        $this->load();
        $this->data->logicalDel();
        $this->data->get();
        self::send(200, array('success' => true, 'data' => $this->record()));
    }


    /**
     * Restore a logically deleted row
     * @return void
     */
    protected function unDel():void{
        $this->load();
        $this->data->logicalUnDel();
        $this->data->get();
        self::send(200, array('success' => true, 'data' => $this->record()));
    }


    /**
     * Hook for the checks specific to a component
     * @param array $errors field => message, to complete
     * @return void
     */
    protected function validate(array &$errors, bool $isNew):void{
    }


    // Helpers
    // ------------------------------------------------------------------------------------------------

    /**
     * Is the complete primary key in the request
     * @return bool
     */
    protected function hasPk():bool{
        foreach(static::PK as $field){
            if(!isset($_GET[$field]) && !isset($this->input[$field])){
                return false;
            }
        }
        return true;
    }


    /**
     * Load in the model the row designated by the primary key of the request
     * @return void
     */
    protected function load():void{
        foreach(static::PK as $field){
            $value = filter_var($_GET[$field] ?? $this->input[$field] ?? null, FILTER_VALIDATE_INT);
            if($value === false || $value === null || $value < 1){
                throw new ApiException(400, 'Missing or invalid parameter '.$field);
            }
            $this->data->$field = $value;
        }
        if(!$this->data->get()){
            throw new ApiException(404, 'Not found');
        }
    }


    /**
     * @return array primary key of the loaded row
     */
    protected function pkValues():array{
        $pk = array();
        foreach(static::PK as $field){
            $pk[$field] = (int)$this->data->$field;
        }
        return $pk;
    }


    /**
     * @return array the row loaded in the model
     */
    protected function record():array{
        $row = array();
        foreach(static::$fieldsNames as $field){
            $row[$field] = $this->data->$field;
        }
        return $this->export($row);
    }


    /**
     * Prepare a row for the answer.
     * The texts are stored html-escaped, like the web interface does: they are decoded here.
     * @return array
     */
    protected function export(array $row):array{
        $out = array();
        foreach(static::$fieldsNames as $field){
            if(in_array($field, static::HIDDEN, true)) continue;

            $value = $row[$field] ?? null;
            if($value !== null){
                $isInt = isset(static::FIELDS[$field]) ? static::FIELDS[$field]['type'] == 'int' : in_array($field, static::PK, true);
                $value = $isInt ? (int)$value : html_entity_decode((string)$value, ENT_QUOTES | ENT_HTML5, 'UTF-8');
            }
            $out[$field] = $value;
        }
        return $out;
    }


    /**
     * Check and convert a value received for a field
     * @return mixed the value to give to the model
     */
    protected function value(string $field, array $spec, $value, array &$errors){
        if(is_bool($value)){
            $value = (int)$value;
        }
        if($value === null || $value === ''){
            if($spec['null']){
                return null;
            }
            if($value === null || $spec['required'] || $spec['type'] == 'int' || isset($spec['enum'])){
                $errors[$field] = 'Must not be empty';
                return $value;
            }
        }
        if(!is_scalar($value)){
            $errors[$field] = 'Invalid value';
            return null;
        }

        if($spec['type'] == 'int'){
            $int = filter_var($value, FILTER_VALIDATE_INT);
            if($int === false){
                $errors[$field] = 'Must be an integer';
            }
            return $int;
        }

        $value = (string)$value;
        if(isset($spec['enum']) && !in_array($value, $spec['enum'], true)){
            $errors[$field] = 'Must be one of: '.implode(', ', $spec['enum']);
        }
        // Same escaping as the forms of the web interface, whose views display the texts as they are stored
        $value = (string)filter_var($value, FILTER_SANITIZE_SPECIAL_CHARS);
        if(isset($spec['max']) && strlen($value) > $spec['max']){
            $errors[$field] = 'Too long, '.$spec['max'].' characters maximum';
        }
        return $value;
    }


    /**
     * Body of the request: JSON, or form fields
     * @return array
     */
    protected function readInput():array{
        if(stripos((string)($_SERVER['CONTENT_TYPE'] ?? ''), 'application/json') !== false){
            $raw = (string)file_get_contents('php://input');
            if(trim($raw) == ''){
                return array();
            }
            $json = json_decode($raw, true);
            if(!is_array($json)){
                throw new ApiException(400, 'Invalid JSON body');
            }
            return $json;
        }
        return $_POST;
    }


    /**
     * Check the access: the API token of config.php (all the rights), or the session of a logged user
     * (rights given by his permissions, see Auth).
     * @return void
     */
    protected function authenticate(string $method, string $task = ''):void{
        // 1. Token: Authorization: Bearer xxx (or X-Api-Key: xxx)
        $token = (string)($_SERVER['HTTP_X_API_KEY'] ?? '');
        $header = (string)($_SERVER['HTTP_AUTHORIZATION'] ?? $_SERVER['REDIRECT_HTTP_AUTHORIZATION'] ?? '');
        if($header == '' && function_exists('apache_request_headers')){
            foreach(apache_request_headers() as $name => $value){
                if(strtolower($name) == 'authorization'){ $header = (string)$value; }
            }
        }
        if(stripos($header, 'Bearer ') === 0){
            $token = trim(substr($header, 7));
        }
        if($token != ''){
            if(defined('API_TOKEN') && API_TOKEN != '' && hash_equals((string)API_TOKEN, $token)){
                return;
            }
            throw new ApiException(401, 'Invalid API token');
        }

        // 2. Session opened by task=login of the user API, or by the login page
        if(!Auth::isLogged()){
            throw new ApiException(401, 'Authentication required');
        }
        // Same rules as the web interface: list and view are the consultation tasks
        $webTasks = array('list' => 'viewlist', 'view' => 'view');
        if(!Auth::can(COMPONENT, $webTasks[$task] ?? $task)){
            throw new ApiException(403, 'Your permissions do not allow this operation');
        }
        // The session cookie is sent by the browser on its own: a request that changes something must prove
        // that it comes from our pages, with the CSRF token of the session
        if($method != 'GET'){
            $csrf = (string)($_SERVER['HTTP_X_CSRF_TOKEN'] ?? $this->input['csrf_token'] ?? $_GET['csrf_token'] ?? '');
            if($csrf == '' || !hash_equals((string)($_SESSION['csrf_token'] ?? ''), $csrf)){
                throw new ApiException(403, 'Invalid CSRF token');
            }
        }
    }


    /**
     * Refuse the HTTP methods not accepted by a task
     * @return void
     */
    protected static function allow(string $method, array $methods):void{
        if(!in_array($method, $methods, true)){
            header('Allow: '.implode(', ', $methods));
            throw new ApiException(405, 'Method not allowed, use '.implode(' or ', $methods));
        }
    }


    /**
     * Send the JSON answer
     * @return void
     */
    public static function send(int $status, array $body):void{
        http_response_code($status);
        header('Content-Type: application/json; charset=utf-8');
        header('Cache-Control: no-store');
        echo json_encode($body, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_INVALID_UTF8_SUBSTITUTE);
    }
}
